jdk:
  - openjdk11
  
stages:
  - phase1
  - phase2

before_install:
  - chmod +x gradlew

addons:
  sonarcloud:
    organization: $SONAR_USER
    token: $SONAR_TOKEN
    
jobs:
  include:
    - stage: compile
      script: ./gradlew sonarqube
    - stage: deploy
      deploy:
        provider: heroku
        api-key: $HEROKU_API_KEY
        app: yagan93
  
 #   - stage: SystemTesting
 #     echo "toBeImplemented"
 #   - stage: DeployingToProductionHeroku
 #     echo "toBeImplemented"


